// utils/data.js — DinoSync 全部 Mock 数据
// 扩展方式：直接在下方数组增加条目，页面自动渲染

// ── 恐龙物种数据 ──
const SPECIMENS = [
  {
    id: '1',
    name: '马门溪龙',
    latinName: 'Mamenchisaurus',
    era: '晚侏罗世',
    eraEn: 'Late Jurassic',
    period: '约 1.6 亿年前',
    location: '四川 · 自贡',
    type: '蜥脚类',
    rarity: 'common',     // common / rare / legendary
    rarityLabel: '普通',
    emoji: '🦕',
    accentColor: '#c8f060',
    description: '中国最著名的恐龙之一，以其极度修长的脖子著称。颈部长度占体长近一半，是已知脊椎动物中颈椎最多的物种之一。发现于四川自贡，为侏罗纪中国的标志性生物。',
    funFact: '它的脖子有 9–14 米长，几乎与一辆公共汽车等长。',
    coords: { latitude: 29.3569, longitude: 104.7784 },
    museumName: '自贡恐龙博物馆',
  },
  {
    id: '2',
    name: '棘鼻青岛龙',
    latinName: 'Tsintaosaurus spinorhinus',
    era: '晚白垩世',
    eraEn: 'Late Cretaceous',
    period: '约 7000 万年前',
    location: '山东 · 莱阳',
    type: '鸭嘴龙类',
    rarity: 'rare',
    rarityLabel: '稀有',
    emoji: '🦖',
    accentColor: '#f0a840',
    description: '因头顶独特的棒状头冠而闻名，是中国鸭嘴龙类的代表。1950年代在山东莱阳发掘，是中国早期古生物研究的重要成果。',
    funFact: '头冠内部中空，科学家推测可能用于发出响亮叫声。',
    coords: { latitude: 36.9171, longitude: 120.7080 },
    museumName: '莱阳白垩纪国家地质公园',
  },
  {
    id: '3',
    name: '中华龙鸟',
    latinName: 'Sinosauropteryx prima',
    era: '早白垩世',
    eraEn: 'Early Cretaceous',
    period: '约 1.25 亿年前',
    location: '辽宁 · 北票',
    type: '兽脚类（有羽毛）',
    rarity: 'legendary',
    rarityLabel: '传奇',
    emoji: '🪶',
    accentColor: '#60d4f0',
    description: '世界上首个被发现保存羽毛印痕的非鸟类恐龙，彻底改变了人类对鸟类起源的认知。1996年在辽宁北票出土，成为恐龙演化研究的里程碑。',
    funFact: '它的羽毛化石保留了颜色信息，研究推测其背部为橙棕色。',
    coords: { latitude: 41.7972, longitude: 120.7543 },
    museumName: '辽宁北票四合屯化石产地',
  },
  {
    id: '4',
    name: '禄丰龙',
    latinName: 'Lufengosaurus huenei',
    era: '早侏罗世',
    eraEn: 'Early Jurassic',
    period: '约 2 亿年前',
    location: '云南 · 禄丰',
    type: '原蜥脚类',
    rarity: 'common',
    rarityLabel: '普通',
    emoji: '🦴',
    accentColor: '#c8f060',
    description: '中国发现的最完整、最古老的恐龙之一，是新中国第一只完整装架展出的恐龙。它代表了恐龙演化的早期阶段。',
    funFact: '1958年被印上了中国邮票，是第一只登上中国国家邮票的恐龙。',
    coords: { latitude: 25.1291, longitude: 102.0792 },
    museumName: '禄丰恐龙国家地质公园',
  },
  {
    id: '5',
    name: '多棘沱江龙',
    latinName: 'Tuojiangosaurus multispinus',
    era: '晚侏罗世',
    eraEn: 'Late Jurassic',
    period: '约 1.5 亿年前',
    location: '四川 · 自贡',
    type: '剑龙类',
    rarity: 'rare',
    rarityLabel: '稀有',
    emoji: '🔺',
    accentColor: '#f0a840',
    description: '中国最具代表性的剑龙类，背部排列有两排尖锐的骨板，尾部有 4 根骨刺。是亚洲剑龙类化石记录中最完整的标本之一。',
    funFact: '尾部的骨刺被称为"沱江刺"，长达 60 厘米，是有效的防御武器。',
    coords: { latitude: 29.3400, longitude: 104.7600 },
    museumName: '自贡恐龙博物馆',
  },
  {
    id: '6',
    name: '华阳龙',
    latinName: 'Huayangosaurus taibaii',
    era: '中侏罗世',
    eraEn: 'Middle Jurassic',
    period: '约 1.65 亿年前',
    location: '四川 · 自贡',
    type: '剑龙类（最古老）',
    rarity: 'legendary',
    rarityLabel: '传奇',
    emoji: '⚡',
    accentColor: '#a880f0',
    description: '迄今已知最古老的剑龙类恐龙，比著名的北美剑龙早 1000 万年。其发现证明了剑龙类起源于亚洲，填补了恐龙演化的关键空缺。',
    funFact: '它同时拥有骨板和骨刺，保留了剑龙类祖先的原始特征。',
    coords: { latitude: 29.3450, longitude: 104.7700 },
    museumName: '自贡恐龙博物馆',
  },
];

// ── 打卡地点数据 ──
const LOCATIONS = [
  {
    id: 'loc1',
    name: '自贡恐龙博物馆',
    type: 'museum',    // museum / wild / urban
    typeLabel: '馆',
    city: '四川·自贡',
    coords: { latitude: 29.3569, longitude: 104.7784 },
    specimenIds: ['1', '5', '6'],
    description: '全球三大恐龙博物馆之一，建于真实化石发掘遗址之上',
    unlockCount: 1823,  // 已有多少人解锁
    isHot: true,
  },
  {
    id: 'loc2',
    name: '中国古动物馆',
    type: 'museum',
    typeLabel: '馆',
    city: '北京',
    coords: { latitude: 39.9165, longitude: 116.3625 },
    specimenIds: ['2', '4'],
    description: '中国科学院古脊椎动物与古人类研究所直属博物馆',
    unlockCount: 3241,
    isHot: true,
  },
  {
    id: 'loc3',
    name: '四合屯化石产地',
    type: 'wild',
    typeLabel: '野',
    city: '辽宁·北票',
    coords: { latitude: 41.7972, longitude: 120.7543 },
    specimenIds: ['3'],
    description: '热河生物群核心产地，中华龙鸟的发现地',
    unlockCount: 234,
    isHot: false,
  },
  {
    id: 'loc4',
    name: '禄丰恐龙地质公园',
    type: 'wild',
    typeLabel: '野',
    city: '云南·禄丰',
    coords: { latitude: 25.1291, longitude: 102.0792 },
    specimenIds: ['4'],
    description: '侏罗纪早期地层出露，禄丰龙的故乡',
    unlockCount: 456,
    isHot: false,
  },
  {
    id: 'loc5',
    name: '上海自然博物馆·快闪点',
    type: 'urban',
    typeLabel: '城',
    city: '上海·静安',
    coords: { latitude: 31.2318, longitude: 121.4693 },
    specimenIds: ['1', '3'],
    description: '城市快闪坐标，限时开放中',
    unlockCount: 892,
    isHot: true,
  },
  {
    id: 'loc6',
    name: '北京自然博物馆',
    type: 'museum',
    typeLabel: '馆',
    city: '北京',
    coords: { latitude: 39.8914, longitude: 116.3972 },
    specimenIds: ['2', '6'],
    description: '中国规模最大的自然历史博物馆之一',
    unlockCount: 1567,
    isHot: false,
  },
];

// ── 成就徽章 ──
const ACHIEVEMENTS = [
  { id: 'a1', emoji: '🦕', name: '初次同步', desc: '完成第一次 Sync 打卡', unlocked: true },
  { id: 'a2', emoji: '🗺️', name: '遗迹探索者', desc: '解锁 3 个不同坐标点', unlocked: false },
  { id: 'a3', emoji: '🔥', name: '连续探险', desc: '连续 7 天打卡', unlocked: false },
  { id: 'a4', emoji: '🪶', name: '羽毛传说', desc: '解锁传奇稀有标本', unlocked: true },
  { id: 'a5', emoji: '🌍', name: '跨省旅行家', desc: '在 3 个不同省份打卡', unlocked: false },
  { id: 'a6', emoji: '💎', name: '古生物研究员', desc: '开通高级会员', unlocked: false },
];

// ── 知识流内容（MVP）──
const KNOWLEDGE_ARTICLES = [
  {
    id: 'k1',
    title: '为什么中华龙鸟改写了恐龙史？',
    tag: '每日一化石',
    readMins: 4,
    specimenId: '3',
    membersOnly: false,
    body: '1996 年在辽宁北票发现的中华龙鸟，首次为非鸟类恐龙提供了羽毛证据。它让“鸟类源于恐龙”的理论从推测走向强证据，也开启了后续大规模羽毛恐龙研究。',
  },
  {
    id: 'k2',
    title: '马门溪龙的长颈，如何供血？',
    tag: '研究速报',
    readMins: 5,
    specimenId: '1',
    membersOnly: false,
    body: '马门溪龙颈椎数量与气腔结构的组合，可能是其长颈适应的关键。研究认为它通过轻量化骨骼与高效循环系统，维持了超长颈部的生理可行性。',
  },
  {
    id: 'k3',
    title: '自贡剑龙类谱系：从华阳龙到沱江龙',
    tag: '深度专题',
    readMins: 7,
    specimenId: '6',
    membersOnly: true,
    body: '华阳龙被认为是已知最早的剑龙类之一，而沱江龙代表了更成熟的装甲与尾刺系统。两者共同勾勒出亚洲剑龙演化的重要支线。',
  },
  {
    id: 'k4',
    title: '化石地层里的“时间误差”是什么？',
    tag: '科普小课',
    readMins: 3,
    specimenId: '4',
    membersOnly: false,
    body: '同一地层中的化石并不总是“同一天”的生命。沉积、搬运与再沉积过程会造成时间混杂。理解这种误差，是读懂古生态重建的第一步。',
  },
];

const LEADERBOARD_MOCK = [
  { id: 'u1', name: '热河追踪者', city: '辽宁', syncCount: 43 },
  { id: 'u2', name: '侏罗纪漫游者', city: '四川', syncCount: 37 },
  { id: 'u3', name: '化石猎人M', city: '北京', syncCount: 31 },
];

// ── 地图标记点配置 ──
// 从 LOCATIONS 生成 wx.map 所需的 markers 格式
function getMapMarkers(unlockedSpecimenIds) {
  return LOCATIONS.map((loc, i) => {
    const hasUnlocked = loc.specimenIds.some(id => unlockedSpecimenIds.includes(id));
    return {
      id: i,
      locationId: loc.id,
      latitude: loc.coords.latitude,
      longitude: loc.coords.longitude,
      title: loc.name,
      // 用不同颜色区分类型（实际项目换为自定义 PNG 图标）
      iconPath: '',
      width: 32,
      height: 32,
      label: {
        content: loc.typeLabel,
        color: loc.type === 'museum' ? '#c8f060' : loc.type === 'wild' ? '#f0a840' : '#60d4f0',
        fontSize: 14,
        borderRadius: 4,
        bgColor: '#1a1e1b',
        padding: 4,
      },
      callout: {
        content: loc.name,
        color: '#e8ede9',
        fontSize: 13,
        borderRadius: 8,
        bgColor: '#1a1e1b',
        padding: 6,
        display: 'BYCLICK',
      },
    };
  });
}

module.exports = {
  SPECIMENS,
  LOCATIONS,
  ACHIEVEMENTS,
  KNOWLEDGE_ARTICLES,
  LEADERBOARD_MOCK,
  getMapMarkers,
};
